# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HMkLIMcIoL_Nz1kum3HdgjszwwL4DcQM
"""

import streamlit as st
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics.pairwise import cosine_similarity

# -----------------------------
# Load Data
# -----------------------------
@st.cache_data
def load_data():
    df = pd.read_csv("movies.csv")

    # Clean column names (remove spaces)
    df.columns = df.columns.str.strip()

    # Rename for easier use
    df = df.rename(columns={
        "Film": "title",
        "Genre": "genre",
        "Audience score %": "audience_score",
        "Rotten Tomatoes %": "rt_score",
        "Profitability": "profitability"
    })

    # Convert numeric columns
    df["audience_score"] = pd.to_numeric(df["audience_score"], errors='coerce')
    df["rt_score"] = pd.to_numeric(df["rt_score"], errors='coerce')
    df["profitability"] = pd.to_numeric(df["profitability"], errors='coerce')

    df = df.dropna()

    return df

movies = load_data()

# -----------------------------
# Feature Engineering
# -----------------------------
@st.cache_data
def compute_similarity(df):
    # Encode Genre (One-hot)
    genre_dummies = pd.get_dummies(df["genre"])

    # Scale numeric features
    scaler = MinMaxScaler()
    numeric_features = scaler.fit_transform(
        df[["audience_score", "rt_score", "profitability"]]
    )

    # Combine features
    features = pd.concat(
        [genre_dummies, pd.DataFrame(numeric_features)],
        axis=1
    )

    similarity = cosine_similarity(features)
    return similarity

similarity = compute_similarity(movies)

# -----------------------------
# Recommendation Function
# -----------------------------
def recommend(movie):
    idx = movies[movies['title'] == movie].index[0]
    scores = list(enumerate(similarity[idx]))

    scores = sorted(scores, key=lambda x: x[1], reverse=True)[1:6]

    recommended = [movies.iloc[i[0]].title for i in scores]
    return recommended

# -----------------------------
# UI
# -----------------------------
st.set_page_config(page_title="Movie Recommender", layout="centered")

st.title("🎬 Movie Recommendation System")

selected_movie = st.selectbox(
    "Choose a movie:",
    movies['title'].values
)

if st.button("Recommend"):
    results = recommend(selected_movie)

    st.subheader("Top Recommendations:")
    for i, movie in enumerate(results, 1):
        st.write(f"{i}. {movie}")