# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HMkLIMcIoL_Nz1kum3HdgjszwwL4DcQM
"""

import streamlit as st
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

st.title("🎬 Movie Recommendation System")

# Load dataset
movies = pd.read_csv("movies.csv")

# Combine features
movies["combined"] = movies["genres"] + " " + movies["keywords"]

# Convert text to vectors
cv = CountVectorizer()
matrix = cv.fit_transform(movies["combined"])

# Similarity matrix
similarity = cosine_similarity(matrix)

# Dropdown
movie_list = movies["title"].values
selected_movie = st.selectbox("Select a movie", movie_list)

# Recommend function
def recommend(movie):
    index = movies[movies["title"] == movie].index[0]
    distances = list(enumerate(similarity[index]))
    sorted_movies = sorted(distances, key=lambda x: x[1], reverse=True)[1:6]

    rec_movies = []
    for i in sorted_movies:
        rec_movies.append(movies.iloc[i[0]].title)
    return rec_movies

# Button
if st.button("Recommend"):
    recommendations = recommend(selected_movie)
    for movie in recommendations:
        st.write(movie)