# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HMkLIMcIoL_Nz1kum3HdgjszwwL4DcQM
"""

import pandas as pd
import streamlit as st
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Load dataset
movies = pd.read_csv("movies.csv")

# Clean data
movies.fillna("", inplace=True)

# Combine relevant features
movies["combined"] = (
    movies["genre"] + " " +
    movies["lead studio"] + " " +
    movies["Audience"].astype(str)
)

# Convert text to vectors
cv = CountVectorizer()
count_matrix = cv.fit_transform(movies["combined"])

# Compute similarity
similarity = cosine_similarity(count_matrix)

# Recommendation function
def recommend(movie):
    movie = movie.lower()

    if movie not in movies["Film"].str.lower().values:
        return ["Movie not found"]

    idx = movies[movies["Film"].str.lower() == movie].index[0]

    scores = list(enumerate(similarity[idx]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)[1:6]

    recommended = [movies.iloc[i[0]]["Film"] for i in scores]
    return recommended


# ---------------- STREAMLIT UI ---------------- #

st.set_page_config(page_title="Movie Recommender", page_icon="🎬")

st.title("🎬 Movie Recommendation System")
st.write("Get similar movies based on genre, studio & audience score!")

# Dropdown
movie_list = movies["Film"].values
selected_movie = st.selectbox("Choose a movie", movie_list)

# Button
if st.button("Recommend"):
    results = recommend(selected_movie)

    st.subheader("Recommended Movies:")

    for i, movie in enumerate(results, start=1):
        st.write(f"{i}. {movie}")